name: Deploy Frontend to Azure Storage

on:
  push:
    branches:
      - main
    paths:
      - 'CourierSA-Frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./CourierSA-Frontend
        run: npm install

      - name: Create .env file
        working-directory: ./CourierSA-Frontend
        run: echo "VITE_API_BASE_URL=https://couriersa2-api-epccfjgagfbwa5cp.southafricanorth-01.azurewebsites.net/api" > .env

      - name: Build
        working-directory: ./CourierSA-Frontend
        run: npm run build

      - name: Upload to Azure Blob Storage
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az storage blob upload-batch \
              --account-name couriersa2frontend \
              --auth-mode key \
              --connection-string "${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" \
              --destination '$web' \
              --source ./CourierSA-Frontend/dist \
              --overwrite